### ISSUE TITLE
Unable to resolve a 2XMM name that is in NED

### ISSUE THREAD

**Issue by DougBurke** [opencadc/cadc-target-resolver#13]
We suspect this may be due to recent changes in the NED service, but (on March 26 2019) I can not resolve a 2XMM name:

```
% curl 'http://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/cadc-target-resolver/find?format=ascii&service=all&cached=true&target=2XMM+J130323.8-634806'
error=Target not found
target=2XMM J130323.8-634806
service=NED, SIMBAD, VIZIER_CDS(null)
coordsys=ICRS
ra=0.0
dec=0.0
time(ms)=0
```

but NED knows about it - https://ned.ipac.caltech.edu/byname?objname=2XMM%20J130323.8-634806&hconst=67.8&omegam=0.308&omegav=0.692

**Comment by at88mph** [comment]
Hmm...  Looking into this one.  Do you know what the recent changes are?

**Comment by at88mph** [comment]
Ah, definitely a change in the VOTable output.  Thanks for reporting this.

**Comment by DougBurke** [comment]
Oh. I was just talking about the fact that NED have (I believe) moved their service and I know some tool-kits don't handle redirects well. I hope I didn't waste too much of your time.
